version: "3.7"
services:
    app:
        build: .
        command: npm install --also=dev
        volumes: 
            - ./:/app
        container_name: app_server
        ports: 
            - 3000:3000
    postgresql:
        image: postgres:12-alpine
        container_name: postgresql_server
        volumes: 
            - ./docker_secrets:/run/secrets
        environment: 
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password